jobs:
  include:
    - stage: test BACKEND
      language: java
      before_script:
        - cd backend/ap-project
        - chmod +x gradlew
      script:
        - ./gradlew check
        - ./gradlew codeCoverageReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
